### ISSUE TITLE
Create a startup.py so that execution is far, far easier

### ISSUE THREAD

**Issue by CShapleigh** [arichards611/Textrpg#16]
Right now in order to start the game one must call:

```
# python
# >>> import story
# >>> story.startup()
```

I just want to be able to call 

```
# python startup.py
```

**Comment by arichards611** [comment]
Currently working in staging

**Comment by CShapleigh** [comment]
Once in master I'll marked as closed!

**Comment by arichards611** [comment]
Done in staging, works otherwise launching wouldn't work.
