### ISSUE TITLE
Rename engine to assetContainer

### ISSUE THREAD

**Issue by CShapleigh** [arichards611/Textrpg#21]
You're gunna hate me but this is a much better name...

Changing should be easy though, pycharm has a 'find and replace all' (ctrl+shift+r on linux/windows) so just replace all instances for engine with assetContainer. 

This will actually benefit #19 because then you can rename the combined `game.py` and `story.py` to `engine.py` because it's what actually handles running the game. `engine.startup()` just sounds so right!

**Comment by arichards611** [comment]
Done in staging, and tested many times otherwise game wouldn't work.
