### ISSUE TITLE
Add a shop

### ISSUE THREAD

**Issue by arichards611** [arichards611/Textrpg#6]
How else are ya gonna get potions and items.

Shop will be it's own function, needs to:
- 'Enter and exit' shop
- Remove Potion's value from players gold
- Add potion to players inventory

**Comment by CShapleigh** [comment]
Perhaps the shop can read/write from a 'database' (probably just a json file) so it can persist stock without having to be 'alive' at all times.

**Comment by arichards611** [comment]
Shop is established in staging, may re-visit later for comment above
